---

- name: Disable Password Authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication' line='PasswordAuthentication no'
  notify: Restart sshd

- name: Disable Root Login
  lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line='PermitRootLogin no'
  notify: Restart sshd
